repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Verificaciones generales de ficheros
      - id: check-yaml
      - id: end-of-file-fixer
        # No excluimos alembic aquí porque
        # estos hooks suelen ser muy rápidos e inofensivos.
      - id: trailing-whitespace
        # Igual, se aplica en todo excepto si tú prefieres excluir la carpeta
        # alembic (si no la quieres tocar en absoluto).
        # exclude: ^alembic/
