name: Unified CI Pipeline

on:
  push:
    branches: ['main', 'develop']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/**'
  pull_request:
    branches: ['main', 'develop']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/**'
  workflow_dispatch: # Permite la ejecución manual

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para SonarCloud

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # FASE 1: CALIDAD DE CÓDIGO (RÁPIDA)
      - name: Code Quality Checks
        id: code-quality
        run: |
          echo "::group::Running Black"
          poetry run black --check app tests || echo "::warning::Black formatting issues found"

          echo "::group::Running isort"
          poetry run isort --check-only --profile black app tests || echo "::warning::Import sorting issues found"

          echo "::group::Running flake8"
          poetry run flake8 app tests || echo "::warning::Linting issues found"

          echo "::group::Running mypy"
          poetry run mypy app tests || echo "::warning::Type checking issues found"

          echo "::group::Running bandit"
          poetry run bandit -r app -x tests || echo "::warning::Security issues found"

      # FASE 2: VERIFICACIÓN DE MIGRACIONES
      - name: Create SQLite Database for Tests
        run: |
          mkdir -p /tmp/test_data
          poetry run python -c "import sqlite3; sqlite3.connect('/tmp/test_data/sqlite.db')"
          echo "SQLITE_URL=sqlite:////tmp/test_data/sqlite.db" >> .env

      - name: Verify Database Migrations
        id: migrations
        env:
          SQLITE_URL: sqlite:////tmp/test_data/sqlite.db
        run: |
          echo "::group::Forward Migrations"
          poetry run alembic upgrade head

          echo "::group::Backward Migrations"
          poetry run alembic downgrade head-1
          poetry run alembic upgrade head

          echo "::group::Checking for missing migrations"
          # Verificar si los modelos están sincronizados con las migraciones
          poetry run alembic revision --autogenerate -m "verification" --check-only || echo "::warning::Models out of sync with migrations"

      # FASE 3: PRUEBAS UNITARIAS Y COBERTURA
      - name: Run Tests with Coverage
        id: tests
        env:
          SQLITE_URL: sqlite:////tmp/test_data/sqlite.db
          API_PREFIX: /api/v1
          PROJECT_NAME: 'FASTAPI KIT STARTER'
          BACKEND_CORS_ORIGINS: '[*]'
          LOGGING_CONFIG_FILE: 'logging.ini'
          PROJECT_VERSION: '0.0.1'
        run: |
          poetry run pytest --cov=app --cov-report=xml --cov-report=term tests/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      # FASE 4: GUARDAR RESULTADOS
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            coverage.xml
            .coverage
          retention-days: 7
